import 'package:flutter/widgets.dart';

Map<String, IconData> t = {
  'threesixty': IconData(0xe577, fontFamily: 'MaterialIcons'),
  'threed_rotation': IconData(0xe84d, fontFamily: 'MaterialIcons'),
  'four_k': IconData(0xe072, fontFamily: 'MaterialIcons'),
  'ac_unit': IconData(0xeb3b, fontFamily: 'MaterialIcons'),
  'access_alarm': IconData(0xe190, fontFamily: 'MaterialIcons'),
  'access_alarms': IconData(0xe191, fontFamily: 'MaterialIcons'),
  'access_time': IconData(0xe192, fontFamily: 'MaterialIcons'),
  'accessibility': IconData(0xe84e, fontFamily: 'MaterialIcons'),
  'accessibility_new': IconData(0xe92c, fontFamily: 'MaterialIcons'),
  'accessible': IconData(0xe914, fontFamily: 'MaterialIcons'),
  'accessible_forward': IconData(0xe934, fontFamily: 'MaterialIcons'),
  'account_balance': IconData(0xe84f, fontFamily: 'MaterialIcons'),
  'account_balance_wallet': IconData(0xe850, fontFamily: 'MaterialIcons'),
  'account_box': IconData(0xe851, fontFamily: 'MaterialIcons'),
  'account_circle': IconData(0xe853, fontFamily: 'MaterialIcons'),
  'adb': IconData(0xe60e, fontFamily: 'MaterialIcons'),
  'add': IconData(0xe145, fontFamily: 'MaterialIcons'),
  'add_a_photo': IconData(0xe439, fontFamily: 'MaterialIcons'),
  'add_alarm': IconData(0xe193, fontFamily: 'MaterialIcons'),
  'add_alert': IconData(0xe003, fontFamily: 'MaterialIcons'),
  'add_box': IconData(0xe146, fontFamily: 'MaterialIcons'),
  'add_call': IconData(0xe0e8, fontFamily: 'MaterialIcons'),
  'add_circle': IconData(0xe147, fontFamily: 'MaterialIcons'),
  'add_circle_outline': IconData(0xe148, fontFamily: 'MaterialIcons'),
  'add_comment': IconData(0xe266, fontFamily: 'MaterialIcons'),
  'add_location': IconData(0xe567, fontFamily: 'MaterialIcons'),
  'add_photo_alternate': IconData(0xe43e, fontFamily: 'MaterialIcons'),
  'add_shopping_cart': IconData(0xe854, fontFamily: 'MaterialIcons'),
  'add_to_home_screen': IconData(0xe1fe, fontFamily: 'MaterialIcons'),
  'add_to_photos': IconData(0xe39d, fontFamily: 'MaterialIcons'),
  'add_to_queue': IconData(0xe05c, fontFamily: 'MaterialIcons'),
  'adjust': IconData(0xe39e, fontFamily: 'MaterialIcons'),
  'airline_seat_flat': IconData(0xe630, fontFamily: 'MaterialIcons'),
  'airline_seat_flat_angled': IconData(0xe631, fontFamily: 'MaterialIcons'),
  'airline_seat_individual_suite':
      IconData(0xe632, fontFamily: 'MaterialIcons'),
  'airline_seat_legroom_extra': IconData(0xe633, fontFamily: 'MaterialIcons'),
  'airline_seat_legroom_normal': IconData(0xe634, fontFamily: 'MaterialIcons'),
  'airline_seat_legroom_reduced': IconData(0xe635, fontFamily: 'MaterialIcons'),
  'airline_seat_recline_extra': IconData(0xe636, fontFamily: 'MaterialIcons'),
  'airline_seat_recline_normal': IconData(0xe637, fontFamily: 'MaterialIcons'),
  'airplanemode_active': IconData(0xe195, fontFamily: 'MaterialIcons'),
  'airplanemode_inactive': IconData(0xe194, fontFamily: 'MaterialIcons'),
  'airplay': IconData(0xe055, fontFamily: 'MaterialIcons'),
  'airport_shuttle': IconData(0xeb3c, fontFamily: 'MaterialIcons'),
  'alarm': IconData(0xe855, fontFamily: 'MaterialIcons'),
  'alarm_add': IconData(0xe856, fontFamily: 'MaterialIcons'),
  'alarm_off': IconData(0xe857, fontFamily: 'MaterialIcons'),
  'alarm_on': IconData(0xe858, fontFamily: 'MaterialIcons'),
  'album': IconData(0xe019, fontFamily: 'MaterialIcons'),
  'all_inclusive': IconData(0xeb3d, fontFamily: 'MaterialIcons'),
  'all_out': IconData(0xe90b, fontFamily: 'MaterialIcons'),
  'alternate_email': IconData(0xe0e6, fontFamily: 'MaterialIcons'),
  'android': IconData(0xe859, fontFamily: 'MaterialIcons'),
  'announcement': IconData(0xe85a, fontFamily: 'MaterialIcons'),
  'apps': IconData(0xe5c3, fontFamily: 'MaterialIcons'),
  'archive': IconData(0xe149, fontFamily: 'MaterialIcons'),
  'arrow_back':
      IconData(0xe5c4, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'arrow_back_ios':
      IconData(0xe5e0, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'arrow_downward': IconData(0xe5db, fontFamily: 'MaterialIcons'),
  'arrow_drop_down': IconData(0xe5c5, fontFamily: 'MaterialIcons'),
  'arrow_drop_down_circle': IconData(0xe5c6, fontFamily: 'MaterialIcons'),
  'arrow_drop_up': IconData(0xe5c7, fontFamily: 'MaterialIcons'),
  'arrow_forward':
      IconData(0xe5c8, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'arrow_forward_ios':
      IconData(0xe5e1, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'arrow_left':
      IconData(0xe5de, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'arrow_right':
      IconData(0xe5df, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'arrow_upward': IconData(0xe5d8, fontFamily: 'MaterialIcons'),
  'art_track': IconData(0xe060, fontFamily: 'MaterialIcons'),
  'aspect_ratio': IconData(0xe85b, fontFamily: 'MaterialIcons'),
  'assessment': IconData(0xe85c, fontFamily: 'MaterialIcons'),
  'assignment':
      IconData(0xe85d, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'assignment_ind': IconData(0xe85e, fontFamily: 'MaterialIcons'),
  'assignment_late': IconData(0xe85f, fontFamily: 'MaterialIcons'),
  'assignment_return':
      IconData(0xe860, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'assignment_returned': IconData(0xe861, fontFamily: 'MaterialIcons'),
  'assignment_turned_in': IconData(0xe862, fontFamily: 'MaterialIcons'),
  'assistant': IconData(0xe39f, fontFamily: 'MaterialIcons'),
  'assistant_photo': IconData(0xe3a0, fontFamily: 'MaterialIcons'),
  'atm': IconData(0xe573, fontFamily: 'MaterialIcons'),
  'attach_file': IconData(0xe226, fontFamily: 'MaterialIcons'),
  'attach_money': IconData(0xe227, fontFamily: 'MaterialIcons'),
  'attachment': IconData(0xe2bc, fontFamily: 'MaterialIcons'),
  'audiotrack': IconData(0xe3a1, fontFamily: 'MaterialIcons'),
  'autorenew': IconData(0xe863, fontFamily: 'MaterialIcons'),
  'av_timer': IconData(0xe01b, fontFamily: 'MaterialIcons'),
  'backspace':
      IconData(0xe14a, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'backup': IconData(0xe864, fontFamily: 'MaterialIcons'),
  'battery_alert': IconData(0xe19c, fontFamily: 'MaterialIcons'),
  'battery_charging_full': IconData(0xe1a3, fontFamily: 'MaterialIcons'),
  'battery_full': IconData(0xe1a4, fontFamily: 'MaterialIcons'),
  'battery_std': IconData(0xe1a5, fontFamily: 'MaterialIcons'),
  'battery_unknown':
      IconData(0xe1a6, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'beach_access': IconData(0xeb3e, fontFamily: 'MaterialIcons'),
  'beenhere': IconData(0xe52d, fontFamily: 'MaterialIcons'),
  'block': IconData(0xe14b, fontFamily: 'MaterialIcons'),
  'bluetooth': IconData(0xe1a7, fontFamily: 'MaterialIcons'),
  'bluetooth_audio': IconData(0xe60f, fontFamily: 'MaterialIcons'),
  'bluetooth_connected': IconData(0xe1a8, fontFamily: 'MaterialIcons'),
  'bluetooth_disabled': IconData(0xe1a9, fontFamily: 'MaterialIcons'),
  'bluetooth_searching': IconData(0xe1aa, fontFamily: 'MaterialIcons'),
  'blur_circular': IconData(0xe3a2, fontFamily: 'MaterialIcons'),
  'blur_linear': IconData(0xe3a3, fontFamily: 'MaterialIcons'),
  'blur_off': IconData(0xe3a4, fontFamily: 'MaterialIcons'),
  'blur_on': IconData(0xe3a5, fontFamily: 'MaterialIcons'),
  'book': IconData(0xe865, fontFamily: 'MaterialIcons'),
  'bookmark': IconData(0xe866, fontFamily: 'MaterialIcons'),
  'bookmark_border': IconData(0xe867, fontFamily: 'MaterialIcons'),
  'border_all': IconData(0xe228, fontFamily: 'MaterialIcons'),
  'border_bottom': IconData(0xe229, fontFamily: 'MaterialIcons'),
  'border_clear': IconData(0xe22a, fontFamily: 'MaterialIcons'),
  'border_color': IconData(0xe22b, fontFamily: 'MaterialIcons'),
  'border_horizontal': IconData(0xe22c, fontFamily: 'MaterialIcons'),
  'border_inner': IconData(0xe22d, fontFamily: 'MaterialIcons'),
  'border_left': IconData(0xe22e, fontFamily: 'MaterialIcons'),
  'border_outer': IconData(0xe22f, fontFamily: 'MaterialIcons'),
  'border_right': IconData(0xe230, fontFamily: 'MaterialIcons'),
  'border_style': IconData(0xe231, fontFamily: 'MaterialIcons'),
  'border_top': IconData(0xe232, fontFamily: 'MaterialIcons'),
  'border_vertical': IconData(0xe233, fontFamily: 'MaterialIcons'),
  'branding_watermark': IconData(0xe06b, fontFamily: 'MaterialIcons'),
  'brightness_1': IconData(0xe3a6, fontFamily: 'MaterialIcons'),
  'brightness_2': IconData(0xe3a7, fontFamily: 'MaterialIcons'),
  'brightness_3': IconData(0xe3a8, fontFamily: 'MaterialIcons'),
  'brightness_4': IconData(0xe3a9, fontFamily: 'MaterialIcons'),
  'brightness_5': IconData(0xe3aa, fontFamily: 'MaterialIcons'),
  'brightness_6': IconData(0xe3ab, fontFamily: 'MaterialIcons'),
  'brightness_7': IconData(0xe3ac, fontFamily: 'MaterialIcons'),
  'brightness_auto': IconData(0xe1ab, fontFamily: 'MaterialIcons'),
  'brightness_high': IconData(0xe1ac, fontFamily: 'MaterialIcons'),
  'brightness_low': IconData(0xe1ad, fontFamily: 'MaterialIcons'),
  'brightness_medium': IconData(0xe1ae, fontFamily: 'MaterialIcons'),
  'broken_image': IconData(0xe3ad, fontFamily: 'MaterialIcons'),
  'brush': IconData(0xe3ae, fontFamily: 'MaterialIcons'),
  'bubble_chart': IconData(0xe6dd, fontFamily: 'MaterialIcons'),
  'bug_report': IconData(0xe868, fontFamily: 'MaterialIcons'),
  'build': IconData(0xe869, fontFamily: 'MaterialIcons'),
  'burst_mode': IconData(0xe43c, fontFamily: 'MaterialIcons'),
  'business': IconData(0xe0af, fontFamily: 'MaterialIcons'),
  'business_center': IconData(0xeb3f, fontFamily: 'MaterialIcons'),
  'cached': IconData(0xe86a, fontFamily: 'MaterialIcons'),
  'cake': IconData(0xe7e9, fontFamily: 'MaterialIcons'),
  'calendar_today': IconData(0xe935, fontFamily: 'MaterialIcons'),
  'calendar_view_day': IconData(0xe936, fontFamily: 'MaterialIcons'),
  'call': IconData(0xe0b0, fontFamily: 'MaterialIcons'),
  'call_end': IconData(0xe0b1, fontFamily: 'MaterialIcons'),
  'call_made':
      IconData(0xe0b2, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'call_merge':
      IconData(0xe0b3, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'call_missed':
      IconData(0xe0b4, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'call_missed_outgoing':
      IconData(0xe0e4, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'call_received':
      IconData(0xe0b5, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'call_split':
      IconData(0xe0b6, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'call_to_action': IconData(0xe06c, fontFamily: 'MaterialIcons'),
  'camera': IconData(0xe3af, fontFamily: 'MaterialIcons'),
  'camera_alt': IconData(0xe3b0, fontFamily: 'MaterialIcons'),
  'camera_enhance': IconData(0xe8fc, fontFamily: 'MaterialIcons'),
  'camera_front': IconData(0xe3b1, fontFamily: 'MaterialIcons'),
  'camera_rear': IconData(0xe3b2, fontFamily: 'MaterialIcons'),
  'camera_roll': IconData(0xe3b3, fontFamily: 'MaterialIcons'),
  'cancel': IconData(0xe5c9, fontFamily: 'MaterialIcons'),
  'card_giftcard': IconData(0xe8f6, fontFamily: 'MaterialIcons'),
  'card_membership': IconData(0xe8f7, fontFamily: 'MaterialIcons'),
  'card_travel': IconData(0xe8f8, fontFamily: 'MaterialIcons'),
  'casino': IconData(0xeb40, fontFamily: 'MaterialIcons'),
  'cast': IconData(0xe307, fontFamily: 'MaterialIcons'),
  'cast_connected': IconData(0xe308, fontFamily: 'MaterialIcons'),
  'category': IconData(0xe574, fontFamily: 'MaterialIcons'),
  'center_focus_strong': IconData(0xe3b4, fontFamily: 'MaterialIcons'),
  'center_focus_weak': IconData(0xe3b5, fontFamily: 'MaterialIcons'),
  'change_history': IconData(0xe86b, fontFamily: 'MaterialIcons'),
  'chat': IconData(0xe0b7, fontFamily: 'MaterialIcons'),
  'chat_bubble': IconData(0xe0ca, fontFamily: 'MaterialIcons'),
  'chat_bubble_outline': IconData(0xe0cb, fontFamily: 'MaterialIcons'),
  'check': IconData(0xe5ca, fontFamily: 'MaterialIcons'),
  'check_box': IconData(0xe834, fontFamily: 'MaterialIcons'),
  'check_box_outline_blank': IconData(0xe835, fontFamily: 'MaterialIcons'),
  'check_circle': IconData(0xe86c, fontFamily: 'MaterialIcons'),
  'check_circle_outline': IconData(0xe92d, fontFamily: 'MaterialIcons'),
  'chevron_left':
      IconData(0xe5cb, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'chevron_right':
      IconData(0xe5cc, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'child_care': IconData(0xeb41, fontFamily: 'MaterialIcons'),
  'child_friendly': IconData(0xeb42, fontFamily: 'MaterialIcons'),
  'chrome_reader_mode':
      IconData(0xe86d, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'class_': IconData(0xe86e, fontFamily: 'MaterialIcons'),
  'clear': IconData(0xe14c, fontFamily: 'MaterialIcons'),
  'clear_all': IconData(0xe0b8, fontFamily: 'MaterialIcons'),
  'close': IconData(0xe5cd, fontFamily: 'MaterialIcons'),
  'closed_caption': IconData(0xe01c, fontFamily: 'MaterialIcons'),
  'cloud': IconData(0xe2bd, fontFamily: 'MaterialIcons'),
  'cloud_circle': IconData(0xe2be, fontFamily: 'MaterialIcons'),
  'cloud_done': IconData(0xe2bf, fontFamily: 'MaterialIcons'),
  'cloud_download': IconData(0xe2c0, fontFamily: 'MaterialIcons'),
  'cloud_off': IconData(0xe2c1, fontFamily: 'MaterialIcons'),
  'cloud_queue': IconData(0xe2c2, fontFamily: 'MaterialIcons'),
  'cloud_upload': IconData(0xe2c3, fontFamily: 'MaterialIcons'),
  'code': IconData(0xe86f, fontFamily: 'MaterialIcons'),
  'collections': IconData(0xe3b6, fontFamily: 'MaterialIcons'),
  'collections_bookmark': IconData(0xe431, fontFamily: 'MaterialIcons'),
  'color_lens': IconData(0xe3b7, fontFamily: 'MaterialIcons'),
  'colorize': IconData(0xe3b8, fontFamily: 'MaterialIcons'),
  'comment': IconData(0xe0b9, fontFamily: 'MaterialIcons'),
  'compare': IconData(0xe3b9, fontFamily: 'MaterialIcons'),
  'compare_arrows': IconData(0xe915, fontFamily: 'MaterialIcons'),
  'computer': IconData(0xe30a, fontFamily: 'MaterialIcons'),
  'confirmation_number': IconData(0xe638, fontFamily: 'MaterialIcons'),
  'contact_mail': IconData(0xe0d0, fontFamily: 'MaterialIcons'),
  'contact_phone': IconData(0xe0cf, fontFamily: 'MaterialIcons'),
  'contacts': IconData(0xe0ba, fontFamily: 'MaterialIcons'),
  'content_copy': IconData(0xe14d, fontFamily: 'MaterialIcons'),
  'content_cut': IconData(0xe14e, fontFamily: 'MaterialIcons'),
  'content_paste': IconData(0xe14f, fontFamily: 'MaterialIcons'),
  'control_point': IconData(0xe3ba, fontFamily: 'MaterialIcons'),
  'control_point_duplicate': IconData(0xe3bb, fontFamily: 'MaterialIcons'),
  'copyright': IconData(0xe90c, fontFamily: 'MaterialIcons'),
  'create': IconData(0xe150, fontFamily: 'MaterialIcons'),
  'create_new_folder': IconData(0xe2cc, fontFamily: 'MaterialIcons'),
  'credit_card': IconData(0xe870, fontFamily: 'MaterialIcons'),
  'crop': IconData(0xe3be, fontFamily: 'MaterialIcons'),
  'crop_16_9': IconData(0xe3bc, fontFamily: 'MaterialIcons'),
  'crop_3_2': IconData(0xe3bd, fontFamily: 'MaterialIcons'),
  'crop_5_4': IconData(0xe3bf, fontFamily: 'MaterialIcons'),
  'crop_7_5': IconData(0xe3c0, fontFamily: 'MaterialIcons'),
  'crop_din': IconData(0xe3c1, fontFamily: 'MaterialIcons'),
  'crop_free': IconData(0xe3c2, fontFamily: 'MaterialIcons'),
  'crop_landscape': IconData(0xe3c3, fontFamily: 'MaterialIcons'),
  'crop_original': IconData(0xe3c4, fontFamily: 'MaterialIcons'),
  'crop_portrait': IconData(0xe3c5, fontFamily: 'MaterialIcons'),
  'crop_rotate': IconData(0xe437, fontFamily: 'MaterialIcons'),
  'crop_square': IconData(0xe3c6, fontFamily: 'MaterialIcons'),
  'dashboard': IconData(0xe871, fontFamily: 'MaterialIcons'),
  'data_usage': IconData(0xe1af, fontFamily: 'MaterialIcons'),
  'date_range': IconData(0xe916, fontFamily: 'MaterialIcons'),
  'dehaze': IconData(0xe3c7, fontFamily: 'MaterialIcons'),
  'delete': IconData(0xe872, fontFamily: 'MaterialIcons'),
  'delete_forever': IconData(0xe92b, fontFamily: 'MaterialIcons'),
  'delete_outline': IconData(0xe92e, fontFamily: 'MaterialIcons'),
  'delete_sweep': IconData(0xe16c, fontFamily: 'MaterialIcons'),
  'departure_board': IconData(0xe576, fontFamily: 'MaterialIcons'),
  'description': IconData(0xe873, fontFamily: 'MaterialIcons'),
  'desktop_mac': IconData(0xe30b, fontFamily: 'MaterialIcons'),
  'desktop_windows': IconData(0xe30c, fontFamily: 'MaterialIcons'),
  'details': IconData(0xe3c8, fontFamily: 'MaterialIcons'),
  'developer_board': IconData(0xe30d, fontFamily: 'MaterialIcons'),
  'developer_mode': IconData(0xe1b0, fontFamily: 'MaterialIcons'),
  'device_hub': IconData(0xe335, fontFamily: 'MaterialIcons'),
  'device_unknown':
      IconData(0xe339, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'devices': IconData(0xe1b1, fontFamily: 'MaterialIcons'),
  'devices_other': IconData(0xe337, fontFamily: 'MaterialIcons'),
  'dialer_sip': IconData(0xe0bb, fontFamily: 'MaterialIcons'),
  'dialpad': IconData(0xe0bc, fontFamily: 'MaterialIcons'),
  'directions': IconData(0xe52e, fontFamily: 'MaterialIcons'),
  'directions_bike': IconData(0xe52f, fontFamily: 'MaterialIcons'),
  'directions_boat': IconData(0xe532, fontFamily: 'MaterialIcons'),
  'directions_bus': IconData(0xe530, fontFamily: 'MaterialIcons'),
  'directions_car': IconData(0xe531, fontFamily: 'MaterialIcons'),
  'directions_railway': IconData(0xe534, fontFamily: 'MaterialIcons'),
  'directions_run': IconData(0xe566, fontFamily: 'MaterialIcons'),
  'directions_subway': IconData(0xe533, fontFamily: 'MaterialIcons'),
  'directions_transit': IconData(0xe535, fontFamily: 'MaterialIcons'),
  'directions_walk': IconData(0xe536, fontFamily: 'MaterialIcons'),
  'disc_full': IconData(0xe610, fontFamily: 'MaterialIcons'),
  'dns': IconData(0xe875, fontFamily: 'MaterialIcons'),
  'do_not_disturb': IconData(0xe612, fontFamily: 'MaterialIcons'),
  'do_not_disturb_alt': IconData(0xe611, fontFamily: 'MaterialIcons'),
  'do_not_disturb_off': IconData(0xe643, fontFamily: 'MaterialIcons'),
  'do_not_disturb_on': IconData(0xe644, fontFamily: 'MaterialIcons'),
  'dock': IconData(0xe30e, fontFamily: 'MaterialIcons'),
  'domain': IconData(0xe7ee, fontFamily: 'MaterialIcons'),
  'done': IconData(0xe876, fontFamily: 'MaterialIcons'),
  'done_all': IconData(0xe877, fontFamily: 'MaterialIcons'),
  'done_outline': IconData(0xe92f, fontFamily: 'MaterialIcons'),
  'donut_large': IconData(0xe917, fontFamily: 'MaterialIcons'),
  'donut_small': IconData(0xe918, fontFamily: 'MaterialIcons'),
  'drafts': IconData(0xe151, fontFamily: 'MaterialIcons'),
  'drag_handle': IconData(0xe25d, fontFamily: 'MaterialIcons'),
  'drive_eta': IconData(0xe613, fontFamily: 'MaterialIcons'),
  'dvr':
      IconData(0xe1b2, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'edit': IconData(0xe3c9, fontFamily: 'MaterialIcons'),
  'edit_attributes': IconData(0xe578, fontFamily: 'MaterialIcons'),
  'edit_location': IconData(0xe568, fontFamily: 'MaterialIcons'),
  'eject': IconData(0xe8fb, fontFamily: 'MaterialIcons'),
  'email': IconData(0xe0be, fontFamily: 'MaterialIcons'),
  'enhanced_encryption': IconData(0xe63f, fontFamily: 'MaterialIcons'),
  'equalizer': IconData(0xe01d, fontFamily: 'MaterialIcons'),
  'error': IconData(0xe000, fontFamily: 'MaterialIcons'),
  'error_outline': IconData(0xe001, fontFamily: 'MaterialIcons'),
  'euro_symbol': IconData(0xe926, fontFamily: 'MaterialIcons'),
  'ev_station': IconData(0xe56d, fontFamily: 'MaterialIcons'),
  'event': IconData(0xe878, fontFamily: 'MaterialIcons'),
  'event_available': IconData(0xe614, fontFamily: 'MaterialIcons'),
  'event_busy': IconData(0xe615, fontFamily: 'MaterialIcons'),
  'event_note':
      IconData(0xe616, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'event_seat': IconData(0xe903, fontFamily: 'MaterialIcons'),
  'exit_to_app': IconData(0xe879, fontFamily: 'MaterialIcons'),
  'expand_less': IconData(0xe5ce, fontFamily: 'MaterialIcons'),
  'expand_more': IconData(0xe5cf, fontFamily: 'MaterialIcons'),
  'explicit': IconData(0xe01e, fontFamily: 'MaterialIcons'),
  'explore': IconData(0xe87a, fontFamily: 'MaterialIcons'),
  'exposure': IconData(0xe3ca, fontFamily: 'MaterialIcons'),
  'exposure_neg_1': IconData(0xe3cb, fontFamily: 'MaterialIcons'),
  'exposure_neg_2': IconData(0xe3cc, fontFamily: 'MaterialIcons'),
  'exposure_plus_1': IconData(0xe3cd, fontFamily: 'MaterialIcons'),
  'exposure_plus_2': IconData(0xe3ce, fontFamily: 'MaterialIcons'),
  'exposure_zero': IconData(0xe3cf, fontFamily: 'MaterialIcons'),
  'extension': IconData(0xe87b, fontFamily: 'MaterialIcons'),
  'face': IconData(0xe87c, fontFamily: 'MaterialIcons'),
  'fast_forward': IconData(0xe01f, fontFamily: 'MaterialIcons'),
  'fast_rewind': IconData(0xe020, fontFamily: 'MaterialIcons'),
  'fastfood': IconData(0xe57a, fontFamily: 'MaterialIcons'),
  'favorite': IconData(0xe87d, fontFamily: 'MaterialIcons'),
  'favorite_border': IconData(0xe87e, fontFamily: 'MaterialIcons'),
  'featured_play_list':
      IconData(0xe06d, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'featured_video':
      IconData(0xe06e, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'feedback': IconData(0xe87f, fontFamily: 'MaterialIcons'),
  'fiber_dvr': IconData(0xe05d, fontFamily: 'MaterialIcons'),
  'fiber_manual_record': IconData(0xe061, fontFamily: 'MaterialIcons'),
  'fiber_new': IconData(0xe05e, fontFamily: 'MaterialIcons'),
  'fiber_pin': IconData(0xe06a, fontFamily: 'MaterialIcons'),
  'fiber_smart_record': IconData(0xe062, fontFamily: 'MaterialIcons'),
  'file_download': IconData(0xe2c4, fontFamily: 'MaterialIcons'),
  'file_upload': IconData(0xe2c6, fontFamily: 'MaterialIcons'),
  'filter': IconData(0xe3d3, fontFamily: 'MaterialIcons'),
  'filter_1': IconData(0xe3d0, fontFamily: 'MaterialIcons'),
  'filter_2': IconData(0xe3d1, fontFamily: 'MaterialIcons'),
  'filter_3': IconData(0xe3d2, fontFamily: 'MaterialIcons'),
  'filter_4': IconData(0xe3d4, fontFamily: 'MaterialIcons'),
  'filter_5': IconData(0xe3d5, fontFamily: 'MaterialIcons'),
  'filter_6': IconData(0xe3d6, fontFamily: 'MaterialIcons'),
  'filter_7': IconData(0xe3d7, fontFamily: 'MaterialIcons'),
  'filter_8': IconData(0xe3d8, fontFamily: 'MaterialIcons'),
  'filter_9': IconData(0xe3d9, fontFamily: 'MaterialIcons'),
  'filter_9_plus': IconData(0xe3da, fontFamily: 'MaterialIcons'),
  'filter_b_and_w': IconData(0xe3db, fontFamily: 'MaterialIcons'),
  'filter_center_focus': IconData(0xe3dc, fontFamily: 'MaterialIcons'),
  'filter_drama': IconData(0xe3dd, fontFamily: 'MaterialIcons'),
  'filter_frames': IconData(0xe3de, fontFamily: 'MaterialIcons'),
  'filter_hdr': IconData(0xe3df, fontFamily: 'MaterialIcons'),
  'filter_list': IconData(0xe152, fontFamily: 'MaterialIcons'),
  'filter_none': IconData(0xe3e0, fontFamily: 'MaterialIcons'),
  'filter_tilt_shift': IconData(0xe3e2, fontFamily: 'MaterialIcons'),
  'filter_vintage': IconData(0xe3e3, fontFamily: 'MaterialIcons'),
  'find_in_page': IconData(0xe880, fontFamily: 'MaterialIcons'),
  'find_replace': IconData(0xe881, fontFamily: 'MaterialIcons'),
  'fingerprint': IconData(0xe90d, fontFamily: 'MaterialIcons'),
  'first_page':
      IconData(0xe5dc, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'fitness_center': IconData(0xeb43, fontFamily: 'MaterialIcons'),
  'flag': IconData(0xe153, fontFamily: 'MaterialIcons'),
  'flare': IconData(0xe3e4, fontFamily: 'MaterialIcons'),
  'flash_auto': IconData(0xe3e5, fontFamily: 'MaterialIcons'),
  'flash_off': IconData(0xe3e6, fontFamily: 'MaterialIcons'),
  'flash_on': IconData(0xe3e7, fontFamily: 'MaterialIcons'),
  'flight': IconData(0xe539, fontFamily: 'MaterialIcons'),
  'flight_land':
      IconData(0xe904, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'flight_takeoff':
      IconData(0xe905, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'flip': IconData(0xe3e8, fontFamily: 'MaterialIcons'),
  'flip_to_back': IconData(0xe882, fontFamily: 'MaterialIcons'),
  'flip_to_front': IconData(0xe883, fontFamily: 'MaterialIcons'),
  'folder': IconData(0xe2c7, fontFamily: 'MaterialIcons'),
  'folder_open': IconData(0xe2c8, fontFamily: 'MaterialIcons'),
  'folder_shared': IconData(0xe2c9, fontFamily: 'MaterialIcons'),
  'folder_special': IconData(0xe617, fontFamily: 'MaterialIcons'),
  'font_download': IconData(0xe167, fontFamily: 'MaterialIcons'),
  'format_align_center': IconData(0xe234, fontFamily: 'MaterialIcons'),
  'format_align_justify': IconData(0xe235, fontFamily: 'MaterialIcons'),
  'format_align_left': IconData(0xe236, fontFamily: 'MaterialIcons'),
  'format_align_right': IconData(0xe237, fontFamily: 'MaterialIcons'),
  'format_bold': IconData(0xe238, fontFamily: 'MaterialIcons'),
  'format_clear': IconData(0xe239, fontFamily: 'MaterialIcons'),
  'format_color_fill': IconData(0xe23a, fontFamily: 'MaterialIcons'),
  'format_color_reset': IconData(0xe23b, fontFamily: 'MaterialIcons'),
  'format_color_text': IconData(0xe23c, fontFamily: 'MaterialIcons'),
  'format_indent_decrease':
      IconData(0xe23d, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'format_indent_increase':
      IconData(0xe23e, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'format_italic': IconData(0xe23f, fontFamily: 'MaterialIcons'),
  'format_line_spacing': IconData(0xe240, fontFamily: 'MaterialIcons'),
  'format_list_bulleted':
      IconData(0xe241, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'format_list_numbered': IconData(0xe242, fontFamily: 'MaterialIcons'),
  'format_list_numbered_rtl': IconData(0xe267, fontFamily: 'MaterialIcons'),
  'format_paint': IconData(0xe243, fontFamily: 'MaterialIcons'),
  'format_quote': IconData(0xe244, fontFamily: 'MaterialIcons'),
  'format_shapes': IconData(0xe25e, fontFamily: 'MaterialIcons'),
  'format_size': IconData(0xe245, fontFamily: 'MaterialIcons'),
  'format_strikethrough': IconData(0xe246, fontFamily: 'MaterialIcons'),
  'format_textdirection_l_to_r': IconData(0xe247, fontFamily: 'MaterialIcons'),
  'format_textdirection_r_to_l': IconData(0xe248, fontFamily: 'MaterialIcons'),
  'format_underlined': IconData(0xe249, fontFamily: 'MaterialIcons'),
  'forum': IconData(0xe0bf, fontFamily: 'MaterialIcons'),
  'forward':
      IconData(0xe154, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'forward_10': IconData(0xe056, fontFamily: 'MaterialIcons'),
  'forward_30': IconData(0xe057, fontFamily: 'MaterialIcons'),
  'forward_5': IconData(0xe058, fontFamily: 'MaterialIcons'),
  'free_breakfast': IconData(0xeb44, fontFamily: 'MaterialIcons'),
  'fullscreen': IconData(0xe5d0, fontFamily: 'MaterialIcons'),
  'fullscreen_exit': IconData(0xe5d1, fontFamily: 'MaterialIcons'),
  'functions':
      IconData(0xe24a, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'g_translate': IconData(0xe927, fontFamily: 'MaterialIcons'),
  'gamepad': IconData(0xe30f, fontFamily: 'MaterialIcons'),
  'games': IconData(0xe021, fontFamily: 'MaterialIcons'),
  'gavel': IconData(0xe90e, fontFamily: 'MaterialIcons'),
  'gesture': IconData(0xe155, fontFamily: 'MaterialIcons'),
  'get_app': IconData(0xe884, fontFamily: 'MaterialIcons'),
  'gif': IconData(0xe908, fontFamily: 'MaterialIcons'),
  'golf_course': IconData(0xeb45, fontFamily: 'MaterialIcons'),
  'gps_fixed': IconData(0xe1b3, fontFamily: 'MaterialIcons'),
  'gps_not_fixed': IconData(0xe1b4, fontFamily: 'MaterialIcons'),
  'gps_off': IconData(0xe1b5, fontFamily: 'MaterialIcons'),
  'grade': IconData(0xe885, fontFamily: 'MaterialIcons'),
  'gradient': IconData(0xe3e9, fontFamily: 'MaterialIcons'),
  'grain': IconData(0xe3ea, fontFamily: 'MaterialIcons'),
  'graphic_eq': IconData(0xe1b8, fontFamily: 'MaterialIcons'),
  'grid_off': IconData(0xe3eb, fontFamily: 'MaterialIcons'),
  'grid_on': IconData(0xe3ec, fontFamily: 'MaterialIcons'),
  'group': IconData(0xe7ef, fontFamily: 'MaterialIcons'),
  'group_add': IconData(0xe7f0, fontFamily: 'MaterialIcons'),
  'group_work': IconData(0xe886, fontFamily: 'MaterialIcons'),
  'hd': IconData(0xe052, fontFamily: 'MaterialIcons'),
  'hdr_off': IconData(0xe3ed, fontFamily: 'MaterialIcons'),
  'hdr_on': IconData(0xe3ee, fontFamily: 'MaterialIcons'),
  'hdr_strong': IconData(0xe3f1, fontFamily: 'MaterialIcons'),
  'hdr_weak': IconData(0xe3f2, fontFamily: 'MaterialIcons'),
  'headset': IconData(0xe310, fontFamily: 'MaterialIcons'),
  'headset_mic': IconData(0xe311, fontFamily: 'MaterialIcons'),
  'headset_off': IconData(0xe33a, fontFamily: 'MaterialIcons'),
  'healing': IconData(0xe3f3, fontFamily: 'MaterialIcons'),
  'hearing': IconData(0xe023, fontFamily: 'MaterialIcons'),
  'help':
      IconData(0xe887, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'help_outline':
      IconData(0xe8fd, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'high_quality': IconData(0xe024, fontFamily: 'MaterialIcons'),
  'highlight': IconData(0xe25f, fontFamily: 'MaterialIcons'),
  'highlight_off': IconData(0xe888, fontFamily: 'MaterialIcons'),
  'history': IconData(0xe889, fontFamily: 'MaterialIcons'),
  'home': IconData(0xe88a, fontFamily: 'MaterialIcons'),
  'hot_tub': IconData(0xeb46, fontFamily: 'MaterialIcons'),
  'hotel': IconData(0xe53a, fontFamily: 'MaterialIcons'),
  'hourglass_empty': IconData(0xe88b, fontFamily: 'MaterialIcons'),
  'hourglass_full': IconData(0xe88c, fontFamily: 'MaterialIcons'),
  'http': IconData(0xe902, fontFamily: 'MaterialIcons'),
  'https': IconData(0xe88d, fontFamily: 'MaterialIcons'),
  'image': IconData(0xe3f4, fontFamily: 'MaterialIcons'),
  'image_aspect_ratio': IconData(0xe3f5, fontFamily: 'MaterialIcons'),
  'import_contacts': IconData(0xe0e0, fontFamily: 'MaterialIcons'),
  'import_export': IconData(0xe0c3, fontFamily: 'MaterialIcons'),
  'important_devices': IconData(0xe912, fontFamily: 'MaterialIcons'),
  'inbox': IconData(0xe156, fontFamily: 'MaterialIcons'),
  'indeterminate_check_box': IconData(0xe909, fontFamily: 'MaterialIcons'),
  'info': IconData(0xe88e, fontFamily: 'MaterialIcons'),
  'info_outline': IconData(0xe88f, fontFamily: 'MaterialIcons'),
  'input':
      IconData(0xe890, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'insert_chart': IconData(0xe24b, fontFamily: 'MaterialIcons'),
  'insert_comment': IconData(0xe24c, fontFamily: 'MaterialIcons'),
  'insert_drive_file': IconData(0xe24d, fontFamily: 'MaterialIcons'),
  'insert_emoticon': IconData(0xe24e, fontFamily: 'MaterialIcons'),
  'insert_invitation': IconData(0xe24f, fontFamily: 'MaterialIcons'),
  'insert_link': IconData(0xe250, fontFamily: 'MaterialIcons'),
  'insert_photo': IconData(0xe251, fontFamily: 'MaterialIcons'),
  'invert_colors': IconData(0xe891, fontFamily: 'MaterialIcons'),
  'invert_colors_off': IconData(0xe0c4, fontFamily: 'MaterialIcons'),
  'iso': IconData(0xe3f6, fontFamily: 'MaterialIcons'),
  'keyboard': IconData(0xe312, fontFamily: 'MaterialIcons'),
  'keyboard_arrow_down': IconData(0xe313, fontFamily: 'MaterialIcons'),
  'keyboard_arrow_left': IconData(0xe314, fontFamily: 'MaterialIcons'),
  'keyboard_arrow_right': IconData(0xe315, fontFamily: 'MaterialIcons'),
  'keyboard_arrow_up': IconData(0xe316, fontFamily: 'MaterialIcons'),
  'keyboard_backspace':
      IconData(0xe317, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'keyboard_capslock': IconData(0xe318, fontFamily: 'MaterialIcons'),
  'keyboard_hide': IconData(0xe31a, fontFamily: 'MaterialIcons'),
  'keyboard_return': IconData(0xe31b, fontFamily: 'MaterialIcons'),
  'keyboard_tab':
      IconData(0xe31c, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'keyboard_voice': IconData(0xe31d, fontFamily: 'MaterialIcons'),
  'kitchen': IconData(0xeb47, fontFamily: 'MaterialIcons'),
  'label':
      IconData(0xe892, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'label_important':
      IconData(0xe937, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'label_outline':
      IconData(0xe893, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'landscape': IconData(0xe3f7, fontFamily: 'MaterialIcons'),
  'language': IconData(0xe894, fontFamily: 'MaterialIcons'),
  'laptop': IconData(0xe31e, fontFamily: 'MaterialIcons'),
  'laptop_chromebook': IconData(0xe31f, fontFamily: 'MaterialIcons'),
  'laptop_mac': IconData(0xe320, fontFamily: 'MaterialIcons'),
  'laptop_windows': IconData(0xe321, fontFamily: 'MaterialIcons'),
  'last_page':
      IconData(0xe5dd, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'launch':
      IconData(0xe895, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'layers': IconData(0xe53b, fontFamily: 'MaterialIcons'),
  'layers_clear': IconData(0xe53c, fontFamily: 'MaterialIcons'),
  'leak_add': IconData(0xe3f8, fontFamily: 'MaterialIcons'),
  'leak_remove': IconData(0xe3f9, fontFamily: 'MaterialIcons'),
  'lens': IconData(0xe3fa, fontFamily: 'MaterialIcons'),
  'library_add': IconData(0xe02e, fontFamily: 'MaterialIcons'),
  'library_books': IconData(0xe02f, fontFamily: 'MaterialIcons'),
  'library_music': IconData(0xe030, fontFamily: 'MaterialIcons'),
  'lightbulb_outline': IconData(0xe90f, fontFamily: 'MaterialIcons'),
  'line_style': IconData(0xe919, fontFamily: 'MaterialIcons'),
  'line_weight': IconData(0xe91a, fontFamily: 'MaterialIcons'),
  'linear_scale': IconData(0xe260, fontFamily: 'MaterialIcons'),
  'link': IconData(0xe157, fontFamily: 'MaterialIcons'),
  'link_off': IconData(0xe16f, fontFamily: 'MaterialIcons'),
  'linked_camera': IconData(0xe438, fontFamily: 'MaterialIcons'),
  'list':
      IconData(0xe896, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'live_help':
      IconData(0xe0c6, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'live_tv': IconData(0xe639, fontFamily: 'MaterialIcons'),
  'local_activity': IconData(0xe53f, fontFamily: 'MaterialIcons'),
  'local_airport': IconData(0xe53d, fontFamily: 'MaterialIcons'),
  'local_atm': IconData(0xe53e, fontFamily: 'MaterialIcons'),
  'local_bar': IconData(0xe540, fontFamily: 'MaterialIcons'),
  'local_cafe': IconData(0xe541, fontFamily: 'MaterialIcons'),
  'local_car_wash': IconData(0xe542, fontFamily: 'MaterialIcons'),
  'local_convenience_store': IconData(0xe543, fontFamily: 'MaterialIcons'),
  'local_dining': IconData(0xe556, fontFamily: 'MaterialIcons'),
  'local_drink': IconData(0xe544, fontFamily: 'MaterialIcons'),
  'local_florist': IconData(0xe545, fontFamily: 'MaterialIcons'),
  'local_gas_station': IconData(0xe546, fontFamily: 'MaterialIcons'),
  'local_grocery_store': IconData(0xe547, fontFamily: 'MaterialIcons'),
  'local_hospital': IconData(0xe548, fontFamily: 'MaterialIcons'),
  'local_hotel': IconData(0xe549, fontFamily: 'MaterialIcons'),
  'local_laundry_service': IconData(0xe54a, fontFamily: 'MaterialIcons'),
  'local_library': IconData(0xe54b, fontFamily: 'MaterialIcons'),
  'local_mall': IconData(0xe54c, fontFamily: 'MaterialIcons'),
  'local_movies': IconData(0xe54d, fontFamily: 'MaterialIcons'),
  'local_offer': IconData(0xe54e, fontFamily: 'MaterialIcons'),
  'local_parking': IconData(0xe54f, fontFamily: 'MaterialIcons'),
  'local_pharmacy': IconData(0xe550, fontFamily: 'MaterialIcons'),
  'local_phone': IconData(0xe551, fontFamily: 'MaterialIcons'),
  'local_pizza': IconData(0xe552, fontFamily: 'MaterialIcons'),
  'local_play': IconData(0xe553, fontFamily: 'MaterialIcons'),
  'local_post_office': IconData(0xe554, fontFamily: 'MaterialIcons'),
  'local_printshop': IconData(0xe555, fontFamily: 'MaterialIcons'),
  'local_see': IconData(0xe557, fontFamily: 'MaterialIcons'),
  'local_shipping': IconData(0xe558, fontFamily: 'MaterialIcons'),
  'local_taxi': IconData(0xe559, fontFamily: 'MaterialIcons'),
  'location_city': IconData(0xe7f1, fontFamily: 'MaterialIcons'),
  'location_disabled': IconData(0xe1b6, fontFamily: 'MaterialIcons'),
  'location_off': IconData(0xe0c7, fontFamily: 'MaterialIcons'),
  'location_on': IconData(0xe0c8, fontFamily: 'MaterialIcons'),
  'location_searching': IconData(0xe1b7, fontFamily: 'MaterialIcons'),
  'lock': IconData(0xe897, fontFamily: 'MaterialIcons'),
  'lock_open': IconData(0xe898, fontFamily: 'MaterialIcons'),
  'lock_outline': IconData(0xe899, fontFamily: 'MaterialIcons'),
  'looks': IconData(0xe3fc, fontFamily: 'MaterialIcons'),
  'looks_3': IconData(0xe3fb, fontFamily: 'MaterialIcons'),
  'looks_4': IconData(0xe3fd, fontFamily: 'MaterialIcons'),
  'looks_5': IconData(0xe3fe, fontFamily: 'MaterialIcons'),
  'looks_6': IconData(0xe3ff, fontFamily: 'MaterialIcons'),
  'looks_one': IconData(0xe400, fontFamily: 'MaterialIcons'),
  'looks_two': IconData(0xe401, fontFamily: 'MaterialIcons'),
  'loop': IconData(0xe028, fontFamily: 'MaterialIcons'),
  'loupe': IconData(0xe402, fontFamily: 'MaterialIcons'),
  'low_priority': IconData(0xe16d, fontFamily: 'MaterialIcons'),
  'loyalty': IconData(0xe89a, fontFamily: 'MaterialIcons'),
  'mail': IconData(0xe158, fontFamily: 'MaterialIcons'),
  'mail_outline': IconData(0xe0e1, fontFamily: 'MaterialIcons'),
  'map': IconData(0xe55b, fontFamily: 'MaterialIcons'),
  'markunread': IconData(0xe159, fontFamily: 'MaterialIcons'),
  'markunread_mailbox': IconData(0xe89b, fontFamily: 'MaterialIcons'),
  'maximize': IconData(0xe930, fontFamily: 'MaterialIcons'),
  'memory': IconData(0xe322, fontFamily: 'MaterialIcons'),
  'menu': IconData(0xe5d2, fontFamily: 'MaterialIcons'),
  'merge_type': IconData(0xe252, fontFamily: 'MaterialIcons'),
  'message': IconData(0xe0c9, fontFamily: 'MaterialIcons'),
  'mic': IconData(0xe029, fontFamily: 'MaterialIcons'),
  'mic_none': IconData(0xe02a, fontFamily: 'MaterialIcons'),
  'mic_off': IconData(0xe02b, fontFamily: 'MaterialIcons'),
  'minimize': IconData(0xe931, fontFamily: 'MaterialIcons'),
  'missed_video_call': IconData(0xe073, fontFamily: 'MaterialIcons'),
  'mms': IconData(0xe618, fontFamily: 'MaterialIcons'),
  'mobile_screen_share':
      IconData(0xe0e7, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'mode_comment': IconData(0xe253, fontFamily: 'MaterialIcons'),
  'mode_edit': IconData(0xe254, fontFamily: 'MaterialIcons'),
  'monetization_on': IconData(0xe263, fontFamily: 'MaterialIcons'),
  'money_off': IconData(0xe25c, fontFamily: 'MaterialIcons'),
  'monochrome_photos': IconData(0xe403, fontFamily: 'MaterialIcons'),
  'mood': IconData(0xe7f2, fontFamily: 'MaterialIcons'),
  'mood_bad': IconData(0xe7f3, fontFamily: 'MaterialIcons'),
  'more': IconData(0xe619, fontFamily: 'MaterialIcons'),
  'more_horiz': IconData(0xe5d3, fontFamily: 'MaterialIcons'),
  'more_vert': IconData(0xe5d4, fontFamily: 'MaterialIcons'),
  'motorcycle': IconData(0xe91b, fontFamily: 'MaterialIcons'),
  'mouse': IconData(0xe323, fontFamily: 'MaterialIcons'),
  'move_to_inbox': IconData(0xe168, fontFamily: 'MaterialIcons'),
  'movie': IconData(0xe02c, fontFamily: 'MaterialIcons'),
  'movie_creation': IconData(0xe404, fontFamily: 'MaterialIcons'),
  'movie_filter': IconData(0xe43a, fontFamily: 'MaterialIcons'),
  'multiline_chart':
      IconData(0xe6df, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'music_note': IconData(0xe405, fontFamily: 'MaterialIcons'),
  'music_video': IconData(0xe063, fontFamily: 'MaterialIcons'),
  'my_location': IconData(0xe55c, fontFamily: 'MaterialIcons'),
  'nature': IconData(0xe406, fontFamily: 'MaterialIcons'),
  'nature_people': IconData(0xe407, fontFamily: 'MaterialIcons'),
  'navigate_before':
      IconData(0xe408, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'navigate_next':
      IconData(0xe409, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'navigation': IconData(0xe55d, fontFamily: 'MaterialIcons'),
  'near_me': IconData(0xe569, fontFamily: 'MaterialIcons'),
  'network_cell': IconData(0xe1b9, fontFamily: 'MaterialIcons'),
  'network_check': IconData(0xe640, fontFamily: 'MaterialIcons'),
  'network_locked': IconData(0xe61a, fontFamily: 'MaterialIcons'),
  'network_wifi': IconData(0xe1ba, fontFamily: 'MaterialIcons'),
  'new_releases': IconData(0xe031, fontFamily: 'MaterialIcons'),
  'next_week':
      IconData(0xe16a, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'nfc': IconData(0xe1bb, fontFamily: 'MaterialIcons'),
  'no_encryption': IconData(0xe641, fontFamily: 'MaterialIcons'),
  'no_sim': IconData(0xe0cc, fontFamily: 'MaterialIcons'),
  'not_interested': IconData(0xe033, fontFamily: 'MaterialIcons'),
  'not_listed_location': IconData(0xe575, fontFamily: 'MaterialIcons'),
  'note':
      IconData(0xe06f, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'note_add': IconData(0xe89c, fontFamily: 'MaterialIcons'),
  'notification_important': IconData(0xe004, fontFamily: 'MaterialIcons'),
  'notifications': IconData(0xe7f4, fontFamily: 'MaterialIcons'),
  'notifications_active': IconData(0xe7f7, fontFamily: 'MaterialIcons'),
  'notifications_none': IconData(0xe7f5, fontFamily: 'MaterialIcons'),
  'notifications_off': IconData(0xe7f6, fontFamily: 'MaterialIcons'),
  'notifications_paused': IconData(0xe7f8, fontFamily: 'MaterialIcons'),
  'offline_bolt': IconData(0xe932, fontFamily: 'MaterialIcons'),
  'offline_pin': IconData(0xe90a, fontFamily: 'MaterialIcons'),
  'ondemand_video': IconData(0xe63a, fontFamily: 'MaterialIcons'),
  'opacity': IconData(0xe91c, fontFamily: 'MaterialIcons'),
  'open_in_browser': IconData(0xe89d, fontFamily: 'MaterialIcons'),
  'open_in_new':
      IconData(0xe89e, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'open_with': IconData(0xe89f, fontFamily: 'MaterialIcons'),
  'outlined_flag': IconData(0xe16e, fontFamily: 'MaterialIcons'),
  'pages': IconData(0xe7f9, fontFamily: 'MaterialIcons'),
  'pageview': IconData(0xe8a0, fontFamily: 'MaterialIcons'),
  'palette': IconData(0xe40a, fontFamily: 'MaterialIcons'),
  'pan_tool': IconData(0xe925, fontFamily: 'MaterialIcons'),
  'panorama': IconData(0xe40b, fontFamily: 'MaterialIcons'),
  'panorama_fish_eye': IconData(0xe40c, fontFamily: 'MaterialIcons'),
  'panorama_horizontal': IconData(0xe40d, fontFamily: 'MaterialIcons'),
  'panorama_vertical': IconData(0xe40e, fontFamily: 'MaterialIcons'),
  'panorama_wide_angle': IconData(0xe40f, fontFamily: 'MaterialIcons'),
  'party_mode': IconData(0xe7fa, fontFamily: 'MaterialIcons'),
  'pause': IconData(0xe034, fontFamily: 'MaterialIcons'),
  'pause_circle_filled': IconData(0xe035, fontFamily: 'MaterialIcons'),
  'pause_circle_outline': IconData(0xe036, fontFamily: 'MaterialIcons'),
  'payment': IconData(0xe8a1, fontFamily: 'MaterialIcons'),
  'people': IconData(0xe7fb, fontFamily: 'MaterialIcons'),
  'people_outline': IconData(0xe7fc, fontFamily: 'MaterialIcons'),
  'perm_camera_mic': IconData(0xe8a2, fontFamily: 'MaterialIcons'),
  'perm_contact_calendar': IconData(0xe8a3, fontFamily: 'MaterialIcons'),
  'perm_data_setting': IconData(0xe8a4, fontFamily: 'MaterialIcons'),
  'perm_device_information': IconData(0xe8a5, fontFamily: 'MaterialIcons'),
  'perm_identity': IconData(0xe8a6, fontFamily: 'MaterialIcons'),
  'perm_media': IconData(0xe8a7, fontFamily: 'MaterialIcons'),
  'perm_phone_msg': IconData(0xe8a8, fontFamily: 'MaterialIcons'),
  'perm_scan_wifi': IconData(0xe8a9, fontFamily: 'MaterialIcons'),
  'person': IconData(0xe7fd, fontFamily: 'MaterialIcons'),
  'person_add': IconData(0xe7fe, fontFamily: 'MaterialIcons'),
  'person_outline': IconData(0xe7ff, fontFamily: 'MaterialIcons'),
  'person_pin': IconData(0xe55a, fontFamily: 'MaterialIcons'),
  'person_pin_circle': IconData(0xe56a, fontFamily: 'MaterialIcons'),
  'personal_video': IconData(0xe63b, fontFamily: 'MaterialIcons'),
  'pets': IconData(0xe91d, fontFamily: 'MaterialIcons'),
  'phone': IconData(0xe0cd, fontFamily: 'MaterialIcons'),
  'phone_android': IconData(0xe324, fontFamily: 'MaterialIcons'),
  'phone_bluetooth_speaker': IconData(0xe61b, fontFamily: 'MaterialIcons'),
  'phone_forwarded': IconData(0xe61c, fontFamily: 'MaterialIcons'),
  'phone_in_talk': IconData(0xe61d, fontFamily: 'MaterialIcons'),
  'phone_iphone': IconData(0xe325, fontFamily: 'MaterialIcons'),
  'phone_locked': IconData(0xe61e, fontFamily: 'MaterialIcons'),
  'phone_missed': IconData(0xe61f, fontFamily: 'MaterialIcons'),
  'phone_paused': IconData(0xe620, fontFamily: 'MaterialIcons'),
  'phonelink': IconData(0xe326, fontFamily: 'MaterialIcons'),
  'phonelink_erase': IconData(0xe0db, fontFamily: 'MaterialIcons'),
  'phonelink_lock': IconData(0xe0dc, fontFamily: 'MaterialIcons'),
  'phonelink_off': IconData(0xe327, fontFamily: 'MaterialIcons'),
  'phonelink_ring': IconData(0xe0dd, fontFamily: 'MaterialIcons'),
  'phonelink_setup': IconData(0xe0de, fontFamily: 'MaterialIcons'),
  'photo': IconData(0xe410, fontFamily: 'MaterialIcons'),
  'photo_album': IconData(0xe411, fontFamily: 'MaterialIcons'),
  'photo_camera': IconData(0xe412, fontFamily: 'MaterialIcons'),
  'photo_filter': IconData(0xe43b, fontFamily: 'MaterialIcons'),
  'photo_library': IconData(0xe413, fontFamily: 'MaterialIcons'),
  'photo_size_select_actual': IconData(0xe432, fontFamily: 'MaterialIcons'),
  'photo_size_select_large': IconData(0xe433, fontFamily: 'MaterialIcons'),
  'photo_size_select_small': IconData(0xe434, fontFamily: 'MaterialIcons'),
  'picture_as_pdf': IconData(0xe415, fontFamily: 'MaterialIcons'),
  'picture_in_picture': IconData(0xe8aa, fontFamily: 'MaterialIcons'),
  'picture_in_picture_alt': IconData(0xe911, fontFamily: 'MaterialIcons'),
  'pie_chart': IconData(0xe6c4, fontFamily: 'MaterialIcons'),
  'pie_chart_outlined': IconData(0xe6c5, fontFamily: 'MaterialIcons'),
  'pin_drop': IconData(0xe55e, fontFamily: 'MaterialIcons'),
  'place': IconData(0xe55f, fontFamily: 'MaterialIcons'),
  'play_arrow': IconData(0xe037, fontFamily: 'MaterialIcons'),
  'play_circle_filled': IconData(0xe038, fontFamily: 'MaterialIcons'),
  'play_circle_outline': IconData(0xe039, fontFamily: 'MaterialIcons'),
  'play_for_work': IconData(0xe906, fontFamily: 'MaterialIcons'),
  'playlist_add':
      IconData(0xe03b, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'playlist_add_check': IconData(0xe065, fontFamily: 'MaterialIcons'),
  'playlist_play': IconData(0xe05f, fontFamily: 'MaterialIcons'),
  'plus_one': IconData(0xe800, fontFamily: 'MaterialIcons'),
  'poll': IconData(0xe801, fontFamily: 'MaterialIcons'),
  'polymer': IconData(0xe8ab, fontFamily: 'MaterialIcons'),
  'pool': IconData(0xeb48, fontFamily: 'MaterialIcons'),
  'portable_wifi_off': IconData(0xe0ce, fontFamily: 'MaterialIcons'),
  'portrait': IconData(0xe416, fontFamily: 'MaterialIcons'),
  'power': IconData(0xe63c, fontFamily: 'MaterialIcons'),
  'power_input': IconData(0xe336, fontFamily: 'MaterialIcons'),
  'power_settings_new': IconData(0xe8ac, fontFamily: 'MaterialIcons'),
  'pregnant_woman': IconData(0xe91e, fontFamily: 'MaterialIcons'),
  'present_to_all': IconData(0xe0df, fontFamily: 'MaterialIcons'),
  'print': IconData(0xe8ad, fontFamily: 'MaterialIcons'),
  'priority_high': IconData(0xe645, fontFamily: 'MaterialIcons'),
  'public': IconData(0xe80b, fontFamily: 'MaterialIcons'),
  'publish': IconData(0xe255, fontFamily: 'MaterialIcons'),
  'query_builder': IconData(0xe8ae, fontFamily: 'MaterialIcons'),
  'question_answer': IconData(0xe8af, fontFamily: 'MaterialIcons'),
  'queue': IconData(0xe03c, fontFamily: 'MaterialIcons'),
  'queue_music':
      IconData(0xe03d, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'queue_play_next': IconData(0xe066, fontFamily: 'MaterialIcons'),
  'radio': IconData(0xe03e, fontFamily: 'MaterialIcons'),
  'radio_button_checked': IconData(0xe837, fontFamily: 'MaterialIcons'),
  'radio_button_unchecked': IconData(0xe836, fontFamily: 'MaterialIcons'),
  'rate_review': IconData(0xe560, fontFamily: 'MaterialIcons'),
  'receipt': IconData(0xe8b0, fontFamily: 'MaterialIcons'),
  'recent_actors': IconData(0xe03f, fontFamily: 'MaterialIcons'),
  'record_voice_over': IconData(0xe91f, fontFamily: 'MaterialIcons'),
  'redeem': IconData(0xe8b1, fontFamily: 'MaterialIcons'),
  'redo':
      IconData(0xe15a, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'refresh': IconData(0xe5d5, fontFamily: 'MaterialIcons'),
  'remove': IconData(0xe15b, fontFamily: 'MaterialIcons'),
  'remove_circle': IconData(0xe15c, fontFamily: 'MaterialIcons'),
  'remove_circle_outline': IconData(0xe15d, fontFamily: 'MaterialIcons'),
  'remove_from_queue': IconData(0xe067, fontFamily: 'MaterialIcons'),
  'remove_red_eye': IconData(0xe417, fontFamily: 'MaterialIcons'),
  'remove_shopping_cart': IconData(0xe928, fontFamily: 'MaterialIcons'),
  'reorder': IconData(0xe8fe, fontFamily: 'MaterialIcons'),
  'repeat': IconData(0xe040, fontFamily: 'MaterialIcons'),
  'repeat_one': IconData(0xe041, fontFamily: 'MaterialIcons'),
  'replay': IconData(0xe042, fontFamily: 'MaterialIcons'),
  'replay_10': IconData(0xe059, fontFamily: 'MaterialIcons'),
  'replay_30': IconData(0xe05a, fontFamily: 'MaterialIcons'),
  'replay_5': IconData(0xe05b, fontFamily: 'MaterialIcons'),
  'reply':
      IconData(0xe15e, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'reply_all':
      IconData(0xe15f, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'report': IconData(0xe160, fontFamily: 'MaterialIcons'),
  'report_off': IconData(0xe170, fontFamily: 'MaterialIcons'),
  'report_problem': IconData(0xe8b2, fontFamily: 'MaterialIcons'),
  'restaurant': IconData(0xe56c, fontFamily: 'MaterialIcons'),
  'restaurant_menu': IconData(0xe561, fontFamily: 'MaterialIcons'),
  'restore': IconData(0xe8b3, fontFamily: 'MaterialIcons'),
  'restore_from_trash': IconData(0xe938, fontFamily: 'MaterialIcons'),
  'restore_page': IconData(0xe929, fontFamily: 'MaterialIcons'),
  'ring_volume': IconData(0xe0d1, fontFamily: 'MaterialIcons'),
  'room': IconData(0xe8b4, fontFamily: 'MaterialIcons'),
  'room_service': IconData(0xeb49, fontFamily: 'MaterialIcons'),
  'rotate_90_degrees_ccw': IconData(0xe418, fontFamily: 'MaterialIcons'),
  'rotate_left': IconData(0xe419, fontFamily: 'MaterialIcons'),
  'rotate_right': IconData(0xe41a, fontFamily: 'MaterialIcons'),
  'rounded_corner': IconData(0xe920, fontFamily: 'MaterialIcons'),
  'router': IconData(0xe328, fontFamily: 'MaterialIcons'),
  'rowing': IconData(0xe921, fontFamily: 'MaterialIcons'),
  'rss_feed': IconData(0xe0e5, fontFamily: 'MaterialIcons'),
  'rv_hookup': IconData(0xe642, fontFamily: 'MaterialIcons'),
  'satellite': IconData(0xe562, fontFamily: 'MaterialIcons'),
  'save': IconData(0xe161, fontFamily: 'MaterialIcons'),
  'save_alt': IconData(0xe171, fontFamily: 'MaterialIcons'),
  'scanner': IconData(0xe329, fontFamily: 'MaterialIcons'),
  'scatter_plot': IconData(0xe268, fontFamily: 'MaterialIcons'),
  'schedule': IconData(0xe8b5, fontFamily: 'MaterialIcons'),
  'school': IconData(0xe80c, fontFamily: 'MaterialIcons'),
  'score': IconData(0xe269, fontFamily: 'MaterialIcons'),
  'screen_lock_landscape': IconData(0xe1be, fontFamily: 'MaterialIcons'),
  'screen_lock_portrait': IconData(0xe1bf, fontFamily: 'MaterialIcons'),
  'screen_lock_rotation': IconData(0xe1c0, fontFamily: 'MaterialIcons'),
  'screen_rotation': IconData(0xe1c1, fontFamily: 'MaterialIcons'),
  'screen_share':
      IconData(0xe0e2, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'sd_card': IconData(0xe623, fontFamily: 'MaterialIcons'),
  'sd_storage': IconData(0xe1c2, fontFamily: 'MaterialIcons'),
  'search': IconData(0xe8b6, fontFamily: 'MaterialIcons'),
  'security': IconData(0xe32a, fontFamily: 'MaterialIcons'),
  'select_all': IconData(0xe162, fontFamily: 'MaterialIcons'),
  'send':
      IconData(0xe163, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'sentiment_dissatisfied': IconData(0xe811, fontFamily: 'MaterialIcons'),
  'sentiment_neutral': IconData(0xe812, fontFamily: 'MaterialIcons'),
  'sentiment_satisfied': IconData(0xe813, fontFamily: 'MaterialIcons'),
  'sentiment_very_dissatisfied': IconData(0xe814, fontFamily: 'MaterialIcons'),
  'sentiment_very_satisfied': IconData(0xe815, fontFamily: 'MaterialIcons'),
  'settings': IconData(0xe8b8, fontFamily: 'MaterialIcons'),
  'settings_applications': IconData(0xe8b9, fontFamily: 'MaterialIcons'),
  'settings_backup_restore': IconData(0xe8ba, fontFamily: 'MaterialIcons'),
  'settings_bluetooth': IconData(0xe8bb, fontFamily: 'MaterialIcons'),
  'settings_brightness': IconData(0xe8bd, fontFamily: 'MaterialIcons'),
  'settings_cell': IconData(0xe8bc, fontFamily: 'MaterialIcons'),
  'settings_ethernet': IconData(0xe8be, fontFamily: 'MaterialIcons'),
  'settings_input_antenna': IconData(0xe8bf, fontFamily: 'MaterialIcons'),
  'settings_input_component': IconData(0xe8c0, fontFamily: 'MaterialIcons'),
  'settings_input_composite': IconData(0xe8c1, fontFamily: 'MaterialIcons'),
  'settings_input_hdmi': IconData(0xe8c2, fontFamily: 'MaterialIcons'),
  'settings_input_svideo': IconData(0xe8c3, fontFamily: 'MaterialIcons'),
  'settings_overscan': IconData(0xe8c4, fontFamily: 'MaterialIcons'),
  'settings_phone': IconData(0xe8c5, fontFamily: 'MaterialIcons'),
  'settings_power': IconData(0xe8c6, fontFamily: 'MaterialIcons'),
  'settings_remote': IconData(0xe8c7, fontFamily: 'MaterialIcons'),
  'settings_system_daydream': IconData(0xe1c3, fontFamily: 'MaterialIcons'),
  'settings_voice': IconData(0xe8c8, fontFamily: 'MaterialIcons'),
  'share': IconData(0xe80d, fontFamily: 'MaterialIcons'),
  'shop': IconData(0xe8c9, fontFamily: 'MaterialIcons'),
  'shop_two': IconData(0xe8ca, fontFamily: 'MaterialIcons'),
  'shopping_basket': IconData(0xe8cb, fontFamily: 'MaterialIcons'),
  'shopping_cart': IconData(0xe8cc, fontFamily: 'MaterialIcons'),
  'short_text':
      IconData(0xe261, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'show_chart':
      IconData(0xe6e1, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'shuffle': IconData(0xe043, fontFamily: 'MaterialIcons'),
  'shutter_speed': IconData(0xe43d, fontFamily: 'MaterialIcons'),
  'signal_cellular_4_bar': IconData(0xe1c8, fontFamily: 'MaterialIcons'),
  'signal_cellular_connected_no_internet_4_bar':
      IconData(0xe1cd, fontFamily: 'MaterialIcons'),
  'signal_cellular_no_sim': IconData(0xe1ce, fontFamily: 'MaterialIcons'),
  'signal_cellular_null': IconData(0xe1cf, fontFamily: 'MaterialIcons'),
  'signal_cellular_off': IconData(0xe1d0, fontFamily: 'MaterialIcons'),
  'signal_wifi_4_bar': IconData(0xe1d8, fontFamily: 'MaterialIcons'),
  'signal_wifi_4_bar_lock': IconData(0xe1d9, fontFamily: 'MaterialIcons'),
  'signal_wifi_off': IconData(0xe1da, fontFamily: 'MaterialIcons'),
  'sim_card': IconData(0xe32b, fontFamily: 'MaterialIcons'),
  'sim_card_alert': IconData(0xe624, fontFamily: 'MaterialIcons'),
  'skip_next': IconData(0xe044, fontFamily: 'MaterialIcons'),
  'skip_previous': IconData(0xe045, fontFamily: 'MaterialIcons'),
  'slideshow': IconData(0xe41b, fontFamily: 'MaterialIcons'),
  'slow_motion_video': IconData(0xe068, fontFamily: 'MaterialIcons'),
  'smartphone': IconData(0xe32c, fontFamily: 'MaterialIcons'),
  'smoke_free': IconData(0xeb4a, fontFamily: 'MaterialIcons'),
  'smoking_rooms': IconData(0xeb4b, fontFamily: 'MaterialIcons'),
  'sms': IconData(0xe625, fontFamily: 'MaterialIcons'),
  'sms_failed': IconData(0xe626, fontFamily: 'MaterialIcons'),
  'snooze': IconData(0xe046, fontFamily: 'MaterialIcons'),
  'sort':
      IconData(0xe164, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'sort_by_alpha': IconData(0xe053, fontFamily: 'MaterialIcons'),
  'spa': IconData(0xeb4c, fontFamily: 'MaterialIcons'),
  'space_bar': IconData(0xe256, fontFamily: 'MaterialIcons'),
  'speaker': IconData(0xe32d, fontFamily: 'MaterialIcons'),
  'speaker_group': IconData(0xe32e, fontFamily: 'MaterialIcons'),
  'speaker_notes': IconData(0xe8cd, fontFamily: 'MaterialIcons'),
  'speaker_notes_off': IconData(0xe92a, fontFamily: 'MaterialIcons'),
  'speaker_phone': IconData(0xe0d2, fontFamily: 'MaterialIcons'),
  'spellcheck': IconData(0xe8ce, fontFamily: 'MaterialIcons'),
  'star': IconData(0xe838, fontFamily: 'MaterialIcons'),
  'star_border': IconData(0xe83a, fontFamily: 'MaterialIcons'),
  'star_half':
      IconData(0xe839, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'stars': IconData(0xe8d0, fontFamily: 'MaterialIcons'),
  'stay_current_landscape': IconData(0xe0d3, fontFamily: 'MaterialIcons'),
  'stay_current_portrait': IconData(0xe0d4, fontFamily: 'MaterialIcons'),
  'stay_primary_landscape': IconData(0xe0d5, fontFamily: 'MaterialIcons'),
  'stay_primary_portrait': IconData(0xe0d6, fontFamily: 'MaterialIcons'),
  'stop': IconData(0xe047, fontFamily: 'MaterialIcons'),
  'stop_screen_share': IconData(0xe0e3, fontFamily: 'MaterialIcons'),
  'storage': IconData(0xe1db, fontFamily: 'MaterialIcons'),
  'store': IconData(0xe8d1, fontFamily: 'MaterialIcons'),
  'store_mall_directory': IconData(0xe563, fontFamily: 'MaterialIcons'),
  'straighten': IconData(0xe41c, fontFamily: 'MaterialIcons'),
  'streetview': IconData(0xe56e, fontFamily: 'MaterialIcons'),
  'strikethrough_s': IconData(0xe257, fontFamily: 'MaterialIcons'),
  'style': IconData(0xe41d, fontFamily: 'MaterialIcons'),
  'subdirectory_arrow_left': IconData(0xe5d9, fontFamily: 'MaterialIcons'),
  'subdirectory_arrow_right': IconData(0xe5da, fontFamily: 'MaterialIcons'),
  'subject':
      IconData(0xe8d2, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'subscriptions': IconData(0xe064, fontFamily: 'MaterialIcons'),
  'subtitles': IconData(0xe048, fontFamily: 'MaterialIcons'),
  'subway': IconData(0xe56f, fontFamily: 'MaterialIcons'),
  'supervised_user_circle': IconData(0xe939, fontFamily: 'MaterialIcons'),
  'supervisor_account': IconData(0xe8d3, fontFamily: 'MaterialIcons'),
  'surround_sound': IconData(0xe049, fontFamily: 'MaterialIcons'),
  'swap_calls': IconData(0xe0d7, fontFamily: 'MaterialIcons'),
  'swap_horiz': IconData(0xe8d4, fontFamily: 'MaterialIcons'),
  'swap_horizontal_circle': IconData(0xe933, fontFamily: 'MaterialIcons'),
  'swap_vert': IconData(0xe8d5, fontFamily: 'MaterialIcons'),
  'swap_vertical_circle': IconData(0xe8d6, fontFamily: 'MaterialIcons'),
  'switch_camera': IconData(0xe41e, fontFamily: 'MaterialIcons'),
  'switch_video': IconData(0xe41f, fontFamily: 'MaterialIcons'),
  'sync': IconData(0xe627, fontFamily: 'MaterialIcons'),
  'sync_disabled': IconData(0xe628, fontFamily: 'MaterialIcons'),
  'sync_problem': IconData(0xe629, fontFamily: 'MaterialIcons'),
  'system_update': IconData(0xe62a, fontFamily: 'MaterialIcons'),
  'system_update_alt': IconData(0xe8d7, fontFamily: 'MaterialIcons'),
  'tab': IconData(0xe8d8, fontFamily: 'MaterialIcons'),
  'tab_unselected': IconData(0xe8d9, fontFamily: 'MaterialIcons'),
  'table_chart': IconData(0xe265, fontFamily: 'MaterialIcons'),
  'tablet': IconData(0xe32f, fontFamily: 'MaterialIcons'),
  'tablet_android': IconData(0xe330, fontFamily: 'MaterialIcons'),
  'tablet_mac': IconData(0xe331, fontFamily: 'MaterialIcons'),
  'tag_faces': IconData(0xe420, fontFamily: 'MaterialIcons'),
  'tap_and_play': IconData(0xe62b, fontFamily: 'MaterialIcons'),
  'terrain': IconData(0xe564, fontFamily: 'MaterialIcons'),
  'text_fields': IconData(0xe262, fontFamily: 'MaterialIcons'),
  'text_format': IconData(0xe165, fontFamily: 'MaterialIcons'),
  'text_rotate_up': IconData(0xe93a, fontFamily: 'MaterialIcons'),
  'text_rotate_vertical': IconData(0xe93b, fontFamily: 'MaterialIcons'),
  'text_rotation_angledown': IconData(0xe93c, fontFamily: 'MaterialIcons'),
  'text_rotation_angleup': IconData(0xe93d, fontFamily: 'MaterialIcons'),
  'text_rotation_down': IconData(0xe93e, fontFamily: 'MaterialIcons'),
  'text_rotation_none': IconData(0xe93f, fontFamily: 'MaterialIcons'),
  'textsms': IconData(0xe0d8, fontFamily: 'MaterialIcons'),
  'texture': IconData(0xe421, fontFamily: 'MaterialIcons'),
  'theaters': IconData(0xe8da, fontFamily: 'MaterialIcons'),
  'thumb_down': IconData(0xe8db, fontFamily: 'MaterialIcons'),
  'thumb_up': IconData(0xe8dc, fontFamily: 'MaterialIcons'),
  'thumbs_up_down': IconData(0xe8dd, fontFamily: 'MaterialIcons'),
  'time_to_leave': IconData(0xe62c, fontFamily: 'MaterialIcons'),
  'timelapse': IconData(0xe422, fontFamily: 'MaterialIcons'),
  'timeline': IconData(0xe922, fontFamily: 'MaterialIcons'),
  'timer': IconData(0xe425, fontFamily: 'MaterialIcons'),
  'timer_10': IconData(0xe423, fontFamily: 'MaterialIcons'),
  'timer_3': IconData(0xe424, fontFamily: 'MaterialIcons'),
  'timer_off': IconData(0xe426, fontFamily: 'MaterialIcons'),
  'title': IconData(0xe264, fontFamily: 'MaterialIcons'),
  'toc':
      IconData(0xe8de, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'today': IconData(0xe8df, fontFamily: 'MaterialIcons'),
  'toll': IconData(0xe8e0, fontFamily: 'MaterialIcons'),
  'tonality': IconData(0xe427, fontFamily: 'MaterialIcons'),
  'touch_app': IconData(0xe913, fontFamily: 'MaterialIcons'),
  'toys': IconData(0xe332, fontFamily: 'MaterialIcons'),
  'track_changes': IconData(0xe8e1, fontFamily: 'MaterialIcons'),
  'traffic': IconData(0xe565, fontFamily: 'MaterialIcons'),
  'train': IconData(0xe570, fontFamily: 'MaterialIcons'),
  'tram': IconData(0xe571, fontFamily: 'MaterialIcons'),
  'transfer_within_a_station': IconData(0xe572, fontFamily: 'MaterialIcons'),
  'transform': IconData(0xe428, fontFamily: 'MaterialIcons'),
  'transit_enterexit': IconData(0xe579, fontFamily: 'MaterialIcons'),
  'translate': IconData(0xe8e2, fontFamily: 'MaterialIcons'),
  'trending_down':
      IconData(0xe8e3, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'trending_flat':
      IconData(0xe8e4, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'trending_up':
      IconData(0xe8e5, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'trip_origin': IconData(0xe57b, fontFamily: 'MaterialIcons'),
  'tune': IconData(0xe429, fontFamily: 'MaterialIcons'),
  'turned_in': IconData(0xe8e6, fontFamily: 'MaterialIcons'),
  'turned_in_not': IconData(0xe8e7, fontFamily: 'MaterialIcons'),
  'tv': IconData(0xe333, fontFamily: 'MaterialIcons'),
  'unarchive': IconData(0xe169, fontFamily: 'MaterialIcons'),
  'undo':
      IconData(0xe166, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'unfold_less': IconData(0xe5d6, fontFamily: 'MaterialIcons'),
  'unfold_more': IconData(0xe5d7, fontFamily: 'MaterialIcons'),
  'update': IconData(0xe923, fontFamily: 'MaterialIcons'),
  'usb': IconData(0xe1e0, fontFamily: 'MaterialIcons'),
  'verified_user': IconData(0xe8e8, fontFamily: 'MaterialIcons'),
  'vertical_align_bottom': IconData(0xe258, fontFamily: 'MaterialIcons'),
  'vertical_align_center': IconData(0xe259, fontFamily: 'MaterialIcons'),
  'vertical_align_top': IconData(0xe25a, fontFamily: 'MaterialIcons'),
  'vibration': IconData(0xe62d, fontFamily: 'MaterialIcons'),
  'video_call': IconData(0xe070, fontFamily: 'MaterialIcons'),
  'video_label': IconData(0xe071, fontFamily: 'MaterialIcons'),
  'video_library': IconData(0xe04a, fontFamily: 'MaterialIcons'),
  'videocam': IconData(0xe04b, fontFamily: 'MaterialIcons'),
  'videocam_off': IconData(0xe04c, fontFamily: 'MaterialIcons'),
  'videogame_asset': IconData(0xe338, fontFamily: 'MaterialIcons'),
  'view_agenda': IconData(0xe8e9, fontFamily: 'MaterialIcons'),
  'view_array': IconData(0xe8ea, fontFamily: 'MaterialIcons'),
  'view_carousel': IconData(0xe8eb, fontFamily: 'MaterialIcons'),
  'view_column': IconData(0xe8ec, fontFamily: 'MaterialIcons'),
  'view_comfy': IconData(0xe42a, fontFamily: 'MaterialIcons'),
  'view_compact': IconData(0xe42b, fontFamily: 'MaterialIcons'),
  'view_day': IconData(0xe8ed, fontFamily: 'MaterialIcons'),
  'view_headline': IconData(0xe8ee, fontFamily: 'MaterialIcons'),
  'view_list':
      IconData(0xe8ef, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'view_module': IconData(0xe8f0, fontFamily: 'MaterialIcons'),
  'view_quilt':
      IconData(0xe8f1, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'view_stream': IconData(0xe8f2, fontFamily: 'MaterialIcons'),
  'view_week': IconData(0xe8f3, fontFamily: 'MaterialIcons'),
  'vignette': IconData(0xe435, fontFamily: 'MaterialIcons'),
  'visibility': IconData(0xe8f4, fontFamily: 'MaterialIcons'),
  'visibility_off': IconData(0xe8f5, fontFamily: 'MaterialIcons'),
  'voice_chat': IconData(0xe62e, fontFamily: 'MaterialIcons'),
  'voicemail': IconData(0xe0d9, fontFamily: 'MaterialIcons'),
  'volume_down': IconData(0xe04d, fontFamily: 'MaterialIcons'),
  'volume_mute': IconData(0xe04e, fontFamily: 'MaterialIcons'),
  'volume_off': IconData(0xe04f, fontFamily: 'MaterialIcons'),
  'volume_up': IconData(0xe050, fontFamily: 'MaterialIcons'),
  'vpn_key': IconData(0xe0da, fontFamily: 'MaterialIcons'),
  'vpn_lock': IconData(0xe62f, fontFamily: 'MaterialIcons'),
  'wallpaper': IconData(0xe1bc, fontFamily: 'MaterialIcons'),
  'warning': IconData(0xe002, fontFamily: 'MaterialIcons'),
  'watch': IconData(0xe334, fontFamily: 'MaterialIcons'),
  'watch_later': IconData(0xe924, fontFamily: 'MaterialIcons'),
  'wb_auto': IconData(0xe42c, fontFamily: 'MaterialIcons'),
  'wb_cloudy': IconData(0xe42d, fontFamily: 'MaterialIcons'),
  'wb_incandescent': IconData(0xe42e, fontFamily: 'MaterialIcons'),
  'wb_iridescent': IconData(0xe436, fontFamily: 'MaterialIcons'),
  'wb_sunny': IconData(0xe430, fontFamily: 'MaterialIcons'),
  'wc': IconData(0xe63d, fontFamily: 'MaterialIcons'),
  'web': IconData(0xe051, fontFamily: 'MaterialIcons'),
  'web_asset': IconData(0xe069, fontFamily: 'MaterialIcons'),
  'weekend': IconData(0xe16b, fontFamily: 'MaterialIcons'),
  'whatshot': IconData(0xe80e, fontFamily: 'MaterialIcons'),
  'widgets': IconData(0xe1bd, fontFamily: 'MaterialIcons'),
  'wifi': IconData(0xe63e, fontFamily: 'MaterialIcons'),
  'wifi_lock': IconData(0xe1e1, fontFamily: 'MaterialIcons'),
  'wifi_tethering': IconData(0xe1e2, fontFamily: 'MaterialIcons'),
  'work': IconData(0xe8f9, fontFamily: 'MaterialIcons'),
  'wrap_text':
      IconData(0xe25b, fontFamily: 'MaterialIcons', matchTextDirection: true),
  'youtube_searched_for': IconData(0xe8fa, fontFamily: 'MaterialIcons'),
  'zoom_in': IconData(0xe8ff, fontFamily: 'MaterialIcons'),
  'zoom_out': IconData(0xe900, fontFamily: 'MaterialIcons'),
  'zoom_out_map': IconData(0xe56b, fontFamily: 'MaterialIcons'),
  'asdasd': IconData(0xe577, fontFamily: 'MaterialIcons'),
};
